import { readCoverageHits, type CoverageHit } from '../coverage/coverage-tracker';
import { inventoryTotals, loadInventory, type Module } from '../coverage/inventory';
export type FunctionalityGap = { id: string; name: string; covered: boolean; coveredBy: string[] };
export type SubModuleGap = { id: string; name: string; covered: boolean; coveredBy: string[]; functionality: FunctionalityGap[]; functionalityCovered: number };
export type ModuleGap = { id: string; name: string; path: string; risk: string; covered: boolean; coveredBy: string[]; subModules: SubModuleGap[]; subModulesCovered: number; functionalityTotal: number; functionalityCovered: number; percent: number };
export type GapReport = { appName: string; totals: { modules: number; subModules: number; functionality: number; nodes: number }; covered: { modules: number; subModules: number; functionality: number; nodes: number }; coveragePercent: number; gapPercent: number; modules: ModuleGap[]; untouchedModules: Array<{ module: string; risk: string }>; untouchedSubModules: Array<{ module: string; subModule: string }>; untouchedFunctionality: Array<{ module: string; subModule: string; functionality: string }> };
const unique = <T,>(items: T[]): T[] => [...new Set(items)];
export function buildGapReport(): GapReport {
  const { appName, modules } = loadInventory(); const hits = readCoverageHits(); const totals = inventoryTotals(modules); const moduleGaps = modules.map((module) => analyseModule(module, hits));
  const covered = { modules: moduleGaps.filter((module) => module.covered).length, subModules: moduleGaps.reduce((n, module) => n + module.subModulesCovered, 0), functionality: moduleGaps.reduce((n, module) => n + module.functionalityCovered, 0), nodes: 0 }; covered.nodes = covered.modules + covered.subModules + covered.functionality;
  return { appName, totals, covered, coveragePercent: totals.nodes ? Math.round((covered.nodes / totals.nodes) * 100) : 0, gapPercent: totals.nodes ? 100 - Math.round((covered.nodes / totals.nodes) * 100) : 0, modules: moduleGaps, untouchedModules: moduleGaps.filter((module) => !module.covered).map((module) => ({ module: module.name, risk: module.risk })), untouchedSubModules: moduleGaps.flatMap((module) => module.subModules.filter((sub) => !sub.covered).map((sub) => ({ module: module.name, subModule: sub.name }))), untouchedFunctionality: moduleGaps.flatMap((module) => module.subModules.flatMap((sub) => sub.functionality.filter((fn) => !fn.covered).map((fn) => ({ module: module.name, subModule: sub.name, functionality: fn.name })))) };
}
function analyseModule(module: Module, hits: CoverageHit[]): ModuleGap {
  const moduleHits = hits.filter((hit) => hit.moduleId === module.id); const coveredBy = unique(moduleHits.map((hit) => hit.testCaseId));
  const subModules = module.subModules.map((sub) => { const functionality = sub.functionality.map((fn) => { const by = unique(moduleHits.filter((hit) => hit.functionalityId === fn.id).map((hit) => hit.testCaseId)); return { id: fn.id, name: fn.name, covered: by.length > 0, coveredBy: by }; }); const subBy = unique(moduleHits.filter((hit) => hit.subModuleId === sub.id).map((hit) => hit.testCaseId)); const functionalityCovered = functionality.filter((fn) => fn.covered).length; return { id: sub.id, name: sub.name, covered: subBy.length > 0 || functionalityCovered > 0, coveredBy: subBy, functionality, functionalityCovered }; });
  const subModulesCovered = subModules.filter((sub) => sub.covered).length; const functionalityTotal = subModules.reduce((n, sub) => n + sub.functionality.length, 0); const functionalityCovered = subModules.reduce((n, sub) => n + sub.functionalityCovered, 0); const total = 1 + subModules.length + functionalityTotal; const done = (coveredBy.length ? 1 : 0) + subModulesCovered + functionalityCovered;
  return { id: module.id, name: module.name, path: module.path, risk: module.risk, covered: coveredBy.length > 0, coveredBy, subModules, subModulesCovered, functionalityTotal, functionalityCovered, percent: Math.round((done / total) * 100) };
}
